spring:
  application:
    name: diorana

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8082}

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE