spring:
  application:
    name: diorana
  
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE